######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 26 02:40:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += src/snakegame.h src/startwindow.h
FORMS += src/snakegame.ui src/startwindow.ui
SOURCES += src/main.cpp src/snakegame.cpp src/startwindow.cpp
RESOURCES += src/resc.qrc
