######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 26 02:40:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snakegame.h startwindow.h
FORMS += snakegame.ui startwindow.ui
SOURCES += main.cpp snakegame.cpp startwindow.cpp
RESOURCES += resc.qrc
